name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76e5137205fedd43cf2a1ce7af8d8a086945e4ba5ce28462690cbb924db5a791"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
