name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b77b0af14fa07e50f2bd8fa1aeb249e30109efc5883b477d67e0d68af8ef197"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
