name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530b249d87b67a777e985d4bab6d76dac55f3393d1932fa2e8674194eb08fcc0"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
