name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b7b5c32a9237a8e2488e4ed1d78b2f514bf8776182739ded3689c2db4bf631"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
