name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "083ab2e7c183e90665ac46c4f3c053bf17d6dd7afb2ae2f16544a4176b0e82b4"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
