name = "Moderne Magick"
author = "Abbie"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d30ecb4c923682f15286ee4db2455791e94e134f686aa5df658960d80bb56f2b"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
